version: "3.9"

services:

  backend:
    build: ./backend
    container_name: campus_backend
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - "3001"
    networks:
      - campus_net

  nginx:
    image: nginx:alpine
    container_name: campus_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./campus-event-hub/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - campus_net

networks:
  campus_net:
    driver: bridge